# dev compose file only db
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
  pgadmin:
    image: dpage/pgadmin4:latest
    ports:
      - "8080:80"
    depends_on:
      - db
    environment:
      PGADMIN_DEFAULT_EMAIL: test@test.com
      PGADMIN_DEFAULT_PASSWORD: mypassword
