# .github/workflows/docker-build.yml
name: Build and Push Docker Images

permissions:
  packages: write
  contents: read

on:
  push:
    branches: [ main ]
    paths:
      - 'apps/**'
      - 'packages/**'
      - '.github/workflows/**'

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      api: ${{ steps.filter.outputs.api }}
      frontend: ${{ steps.filter.outputs.frontend }}
      websocket: ${{ steps.filter.outputs.websocket }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            api:
              - 'apps/api/**'
              - 'packages/**'  # If you have shared code
            frontend:
              - 'apps/frontend/**'
              - 'packages/**'  # If you have shared code
            websocket:
              - 'apps/websocket/**'
              - 'packages/**'  # If you have shared code

  build-api:
    needs: changes
    if: ${{ needs.changes.outputs.api == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: kmate19
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and push Api
        uses: docker/build-push-action@v5
        with:
          context: .
          file: apps/api/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/api:latest
            ghcr.io/${{ github.repository }}/api:${{ github.sha }}

  build-frontend:
    needs: changes
    if: ${{ needs.changes.outputs.frontend == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: kmate19
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and push Frontend
        uses: docker/build-push-action@v5
        with:
          context: .
          file: apps/frontend/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/frontend:latest
            ghcr.io/${{ github.repository }}/frontend:${{ github.sha }}

  build-websocket:
    needs: changes
    if: ${{ needs.changes.outputs.websocket == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: kmate19
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and push Websocket
        uses: docker/build-push-action@v5
        with:
          context: .
          file: apps/websocket/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/websocket:latest
            ghcr.io/${{ github.repository }}/websocket:${{ github.sha }}
